## This rule redirects to an external API

[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}
